### ISSUE TITLE
Cannot integrate in express server with no options passed.

### ISSUE THREAD

**Issue by awochna** [lennym/express-healthcheck#1]
Given the following example:

``` javascript
var express = require('express');
var healthcheck = require('express-healthcheck');
var app = express();

app.use('/health', healthcheck());

app.listen(3000);
```

I would expect to be able to navigate to '/health' and receive a JSON object of the server's uptime, as described in the README. This happens, but also crashes the server with the following error:

```
timers.js:383
      immediate._onImmediate();
                ^

TypeError: immediate._onImmediate is not a function
```

**Comment by lennym** [comment]
Thanks for raising an issue @awochna 

Would you mind letting me know what node version you're running on?

**Comment by awochna** [comment]
5.7, although I can confirm my CI test on 4.2 is also failing with the same message.

**Comment by lennym** [comment]
Thanks. As you can probably tell, I wrote this quite a while ago, and was still running 0.10 when I wrote it. I think the behaviour around `setImmediate` has changed in Node since then.

I'll have a look at your PR and set up a travis to run it against all versions.

Thanks again for contributing.

**Comment by awochna** [comment]
No problem, thanks for creating this module. It looks really well thought out!

**Comment by awochna** [comment]
Great! Thanks for releasing a new version so quickly too!

**Comment by lennym** [comment]
You were lucky to catch me in the middle of a particularly dull meeting ;-)

**Comment by awochna** [comment]
Those are always the most productive :stuck_out_tongue:
